import { createFileRoute } from "@tanstack/react-router";
import { Activity, KeyRound, UserPlus, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Kicker, Panel, SectionHeader } from "@/components/app-shell";
export const Route = createFileRoute("/_authenticated/admin")({ component: AdminPage });
const roles = [["Owner","Everything, including integrations and access","1 seat"],["Manager","Tasks, phases, logs, and market notes","0 seats"],["Contributor","Own tasks and daily logs","0 seats"],["Viewer","Read-only project visibility","0 seats"]];
function AdminPage() { return <div><SectionHeader eyebrow="ADMIN / RBAC" title="Access with intent" description="The workspace is private by default. Keep the team small while the CaseFlow pilot is still finding its shape." action={<Button><UserPlus className="mr-2 h-4 w-4"/> Invite teammate</Button>} /><div className="grid gap-5 lg:grid-cols-[1.2fr_1fr]"><Panel><div className="flex items-center gap-3"><Users className="h-5 w-5 text-primary"/><div><Kicker>Roles</Kicker><h2 className="mt-1 text-lg font-semibold">Permission model</h2></div></div><div className="mt-5 space-y-3">{roles.map(([name,desc,count])=><div className="flex items-center gap-4 rounded border border-border p-3" key={name}><div className="grid h-8 w-8 place-items-center rounded bg-accent text-primary"><KeyRound className="h-4 w-4"/></div><div className="min-w-0 flex-1"><div className="text-sm font-semibold">{name}</div><div className="text-xs text-muted-foreground">{desc}</div></div><Badge variant="outline" className="text-[10px]">{count}</Badge></div>)}</div></Panel><Panel><Kicker>Current workspace</Kicker><h2 className="mt-1 text-lg font-semibold">Formiva internal team</h2><div className="mt-5 space-y-3"><div className="flex gap-3"><Input placeholder="teammate@email.com"/><Button variant="outline">Add</Button></div><p className="text-xs text-muted-foreground">Invites stay pending until the recipient accepts and signs in.</p><div className="mt-6 flex items-center gap-3 border-t border-border pt-5"><Activity className="h-4 w-4 text-emerald-400"/><div><div className="text-sm">Audit logging enabled</div><div className="text-xs text-muted-foreground">Role changes and project mutations are recorded.</div></div></div></div></Panel></div><Panel className="mt-5"><Kicker>Recent audit trail</Kicker><div className="mt-4 grid gap-3 md:grid-cols-3">{[["Workspace created","Owner","today"],["RBAC policy loaded","System","today"],["GitHub connection detected","Owner","today"]].map(([a,b,c])=><div className="rounded border border-border p-3" key={a}><div className="text-sm">{a}</div><div className="mt-2 flex justify-between text-[10px] text-muted-foreground"><span>{b}</span><span className="mono">{c}</span></div></div>)}</div></Panel></div>; }
