import { createFileRoute } from "@tanstack/react-router";
import { ExternalLink, Plus, RefreshCw } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Kicker, Panel, SectionHeader } from "@/components/app-shell";
export const Route = createFileRoute("/_authenticated/market")({ component: MarketPage });
const initial = [{name:"Jotform", angle:"Fast forms", note:"Broad and approachable, less opinionated about operational workflow.", ours:"CaseFlow + audit trail"},{name:"Formstack", angle:"Enterprise forms", note:"Strong forms and documents, heavier configuration surface.", ours:"Focused onboarding workflow"},{name:"Power Automate", angle:"Automation fabric", note:"Flexible inside Microsoft ecosystems, requires assembly.", ours:"Opinionated end-to-end flow"},{name:"Zapier", angle:"App connections", note:"Excellent breadth, weak case ownership and evidence model.", ours:"Structured cases and gates"}];
function MarketPage() { const [rows,setRows] = useState(initial); const [digest,setDigest] = useState("The opening is not another form builder. Formiva can win by owning the operational middle: clear handoffs, approvals, evidence, and a measurable onboarding outcome."); const [editing,setEditing] = useState(false); return <div><SectionHeader eyebrow="MARKET / POSITIONING" title="Keep the edge current" description="A working comparison, not a static report. Add your own notes as the pilot reveals where CaseFlow is meaningfully different." action={<Button variant="outline" onClick={() => setEditing(!editing)}>{editing ? "Done editing" : "Edit notes"}</Button>} /><Panel><div className="flex items-start justify-between gap-4"><div><Kicker>Working digest</Kicker><h2 className="mt-1 text-lg font-semibold">Own the workflow, not just the form.</h2></div><Button size="sm" variant="outline" onClick={() => setDigest("Refresh queued — add the latest pilot evidence before accepting a new digest.")}><RefreshCw className="mr-2 h-3.5 w-3.5" /> Refresh</Button></div><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">{digest}</p></Panel><div className="mt-5 overflow-x-auto rounded-lg border border-border"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-card text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="p-4">Competitor</th><th className="p-4">Their angle</th><th className="p-4">Read</th><th className="p-4">Our position</th></tr></thead><tbody>{rows.map((row,i) => <tr className="border-t border-border" key={row.name}><td className="p-4 font-semibold">{row.name}</td><td className="p-4 text-muted-foreground">{row.angle}</td><td className="p-4">{editing ? <Input value={row.note} onChange={e => setRows(rows.map((r,j)=>j===i?{...r,note:e.target.value}:r))} /> : row.note}</td><td className="p-4 text-primary">{row.ours}</td></tr>)}</tbody></table></div><Button variant="ghost" className="mt-4 text-primary"><Plus className="mr-2 h-4 w-4" /> Add competitor note <ExternalLink className="ml-2 h-3.5 w-3.5" /></Button></div>; }
