import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight, CheckCircle2, CircleDashed } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Kicker, Panel, SectionHeader } from "@/components/app-shell";
export const Route = createFileRoute("/_authenticated/use-cases")({ component: UseCasesPage });
const cases = [
  ["UC-01","Employee onboarding","Capture a complete, structured request and route it to the right owner.","validating"], ["UC-02","Approval orchestration","Make approvals explicit, sequenced, and easy to audit.","not started"], ["UC-03","Evidence collection","Keep supporting documents and decisions attached to the case.","not started"], ["UC-04","Exception handling","Turn blockers into visible work instead of buried messages.","validating"], ["UC-05","Status communication","Give requesters a clear, current view of progress.","not started"], ["UC-06","Rules and policy","Encode repeatable checks without forcing teams into spreadsheets.","not started"], ["UC-07","Handoffs","Reduce dropped context between HR, IT, and managers.","not started"], ["UC-08","Audit trail","Answer who changed what, when, and why.","not started"], ["UC-09","Measurement","Track cycle time, rework, and adoption.","not started"], ["UC-10","Reusable workflows","Turn the pilot into a repeatable CaseFlow pattern.","not started"],
];
function UseCasesPage() { return <div><SectionHeader eyebrow="USE CASES / SALES WAVES" title="What CaseFlow must prove" description="Each use case is a product hypothesis with a gate condition. Mark it validating only when there is evidence from the current build." /><div className="grid gap-4 md:grid-cols-2">{cases.map(([id,title,body,status]) => <Panel key={id} className="p-4"><div className="flex items-center justify-between"><span className="mono text-[10px] text-primary">{id}</span><Badge variant="outline" className="text-[10px] uppercase">{status}</Badge></div><h2 className="mt-4 font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{body}</p><div className="mt-4 flex items-center gap-2 text-xs text-muted-foreground">{status === "validating" ? <CheckCircle2 className="h-3.5 w-3.5 text-emerald-400" /> : <CircleDashed className="h-3.5 w-3.5" />}Gate condition <ArrowUpRight className="ml-auto h-3.5 w-3.5" /></div></Panel>)}</div><Panel className="mt-5"><Kicker>Commercial sequence</Kicker><div className="mt-4 grid gap-3 md:grid-cols-5">{["Internal pilot","Design partners","Sensitive workflows","Operational scale","Public edition"].map((item,i) => <div key={item} className="rounded border border-border p-3"><div className="mono text-xs text-primary">WAVE 0{i+1}</div><div className="mt-2 text-sm">{item}</div></div>)}</div></Panel></div>; }
